# Generated by Django 2.2.3 on 2019-07-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20190715_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('keywords', models.ManyToManyField(related_name='negativekeyword', to='bot.Keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negativekeyword', to='bot.User')),
            ],
        ),
    ]
