# Generated by Django 2.2.3 on 2020-01-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_negativekeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keys', models.ManyToManyField(related_name='groups', to='bot.Keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='bot.User')),
            ],
        ),
    ]
