# Generated by Django 2.2.3 on 2020-01-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_keywordsgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='keywordsgroup',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
